### PR TITLE
su-tunnel for NetBeans added.

### PR DESCRIPTION
**Pull request by Nazz78**
This is an extended version of Noel's original script, which was made
since I could not find a way to run the script with the currently opened
file. What it does? It checks which .rb script (in specified folders)
was changed last and it then runs it.

If someone has a better way, please let me know!

Message to Noel:
For now I've committed this script to NetBeans branch. Merge it with master if or when you find it appropriate. It works for me.

### CODE REVIEW

**Comment by noelwarr** [comment]
Hi there Jernej.

Thanks for taking an interest in the tunnel and adding to it.  I will merge
it into my branch but probably sometime next month.  I'm in the middle of
moving house.  Infact my wife nearly murdered me for attending Lisbon.

I've already been emailed by a netbean user that is trying to setup sublime
and not having much luck.  I'll point him in the direction of your fork.

See you round.

2013/10/19 Jernej Vidmar notifications@github.com

> This is an extended version of Noel's original script, which was made
> since I could not find a way to run the script with the currently opened
> file. What it does? It checks which .rb script (in specified folders)
> was changed last and it then runs it.
> 
> If someone has a better way, please let me know!
> 
> Message to Noel:
> For now I've committed this script to NetBeans branch. Merge it with
> 
> ## master if or when you find it appropriate. It works for me.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/Nazz78/su-tunnel NetBeans
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/noelwarr/su-tunnel/pull/2
> Commit Summary
> - su-tunnel for NetBeans added.
> 
> File Changes
> - _A_ tunnel_ide_for_netbeans.rbhttps://github.com/noelwarr/su-tunnel/pull/2/files#diff-0(82)
> 
> Patch Links:
> - https://github.com/noelwarr/su-tunnel/pull/2.patch
> - https://github.com/noelwarr/su-tunnel/pull/2.diff

**Comment by Nazz78** [comment]
Hi Noel,

no worries, just merge it when you have the time. In the meantime, we 
might even improve it a bit - I'm trying to use your original script by 
just sending the filename of file which is focused in tabs, but I can 
not find the way...

Best regards,
Jernej

Dne 20.10.2013 16:34, piše Noel:

**Comment by noelwarr** [comment]
Hi Jernej

I pulled your changes into a new branch (
https://github.com/noelwarr/su-tunnel/tree/pr/2).  I changed a couple of
things.  I renamed your script and put it in a netbeans folder.  I also
removed all the socket stuff from it.  This means your script now finds the
newest file and then issues a system command to run the tunnel_ide.rb
script.  To get it to work you will need to place both sketchup_build.rb
and tunnel_ide.rb in the same folder wherever you need to put it in
netbeans.

If I understand correctly, you are adding a tunnel script to every project
you want to use it in.  Because I don't have netbeans, could you...

1) test to see if my refactoring still works

2) edit the README to include netbeans instructions and then send me a pull
request.

Thanks for everything.  See ya round.

**Comment by Nazz78** [comment]
Hi Noel,

thanks for the update. I'll check your updates ASAP and get back to you once I have more info. Preferably with the README updated :-)

Cheers,
Jernej

**Comment by noelwarr** [comment]
Turning down this pull request as it was requesting to merge into master.  I think all the related changes are in the later pull request.  At least I hope so.

**Pull request closed without merging**
